config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users, controllers: {sessions: "sessions", passwords: "passwords"}

  resources :roles
  resources :users, except: :create
  get 'create_new_user' => 'users#new', as: :create_new_user
  post 'create_user' => 'users#create', as: :create_user
  get 'create_new_role' => 'roles#new', as: :create_new_role
  get 'create_new_project' => 'projects#new', as: :create_new_project

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :role_type

  belongs_to :role

  validates :first_name, :last_name, :presence => true

  before_save :assign_role

  def assign_role
    self.role = Role.find_by name: "Regular" if self.role.nil?
  end

  def admin?
    self.role.name == "Admin"
  end

  def regular?
    self.role.name == "Regular"
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def as_json(options={})
    super(:include => [:role])
  end

  def attributes
    @role_type = self.role.name if self.role.present?
    super.merge({ 'role_type' => @role_type })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_authorize_resource :only => [:show, :edit, :index, :update]
  before_action :authorize_admin, only: [:create, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:role).all
    respond_with(@users) do |format|
      format.json { render :json => {:list => @users.as_json, :current_user => current_user.as_json} }
      format.html
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_with(@user) do |format|
      format.json { render :json => {:user => @user.as_json, :current_user => current_user.as_json} }
      format.html
    end
  end

  # GET /users/new
  def new
    @user = User.new
    @minimum_password_length = 8
    #roles = Role.all
    respond_with(@user) do |format|
      format.json { render :json => {:user => @user.as_json, :is_admin => current_user.admin?, :roles => role_names} }
      format.html
    end
  end

  # GET /users/1/edit
  def edit
    #roles = Role.all
    respond_with(@user) do |format|
      format.json { render :json => {:user => @user.as_json, :is_admin => current_user.admin?, :current_user => current_user, :roles => role_names} }
      format.html
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user.as_json, notice: 'User was successfully created.' }
        @user.send_reset_password_instructions
      else
        format.html { render :new }
        format.json { render json: @user.errors.full_messages, status: :unprocessable_entity  }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user.as_json, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.admin?
      respond_to do |format|
        format.html { redirect_to users_url, alert: 'Admin can not be deleted.' }
        format.json { head :no_content }
      end
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.includes(:role).find(params[:id])
    render json: {status: :not_found} unless @user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user, url: create_user_path) do |f|
  - if @user.errors.any?
    = ar_errors_custom_view(@user)
  .field
    = f.label :first_name
    %br/
    = f.text_field :first_name, :class => 'form-control'
  .field
    = f.label :last_name
    %br/
    = f.text_field :last_name, :class => 'form-control'
  - if current_user.admin?
    .field
      = f.label :role_id
      %br/
      = f.select(:role_id, role_names, {}, { :class => 'form-control' })
  .field
    = f.label :email
    %br/
    = f.email_field :email, autofocus: true, :class => 'form-control'
  .field
    = f.label :password
    - if @minimum_password_length
      %em
        (#{@minimum_password_length} characters minimum)
    %br/
    = f.password_field :password, autocomplete: "off", :class => 'form-control'
  .field
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation, autocomplete: "off", :class => 'form-control'
  .actions
    = f.submit "Create User", :class => "btn btn-default"

app/views/users/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h2 Listing Users
.table-responsive
  %table.table.table-bordered
    %thead
      %tr
        %th First name
        %th Last name
        %th Role
        %th Actions
    %tbody
      - @users.each do |user|
        %tr
          %td= user.first_name
          %td= user.last_name
          %td= user.role.name
          %td
            = link_to 'Show', user, :class => "btn btn-success btn-sm active", :role => "button"
            = link_to 'Edit', edit_user_registration_url(current_user), :class => "btn btn-warning btn-sm active", :role => "button"
            = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm active", :role => "button"

= link_to 'New User', create_new_user_path

app/views/users/new.html.haml
%h2 New User
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.haml
%p
  %strong First name:
  = @user.first_name
%p
  %strong Last name:
  = @user.last_name
%p
  %strong Role:
  = @user.role.name
= link_to 'Edit', edit_user_registration_url(current_user)
|
= link_to 'Back', users_path