config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users, controllers: {sessions: "sessions", passwords: "passwords"}

  resources :roles
  resources :users, except: :create
  get 'create_new_user' => 'users#new', as: :create_new_user
  post 'create_user' => 'users#create', as: :create_user
  get 'create_new_role' => 'roles#new', as: :create_new_role
  get 'create_new_project' => 'projects#new', as: :create_new_project

  root 'home#index'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  validates :name, :description, :presence => true
  validates :name, :uniqueness => true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :authorize_admin
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
    respond_with(@roles) do |format|
      format.json { render :json => {:list => @roles.as_json, :current_user => current_user.as_json} }
      format.html
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    respond_with(@role) do |format|
      format.json { render json: @role.as_json }
      format.html
    end
  end

  # GET /roles/new
  def new
    @role = Role.new
    respond_with(@role) do |format|
      format.json { render :json => {:role => @role.as_json, :is_admin => current_user.admin?} }
      format.html
    end
  end

  # GET /roles/1/edit
  def edit
    respond_with(@role) do |format|
      format.json { render :json => {:role => @role.as_json, :is_admin => current_user.admin?} }
      format.html
    end
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role.as_json }
      else
        format.html { render :new }
        format.json { render json: @role.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role.as_json }
      else
        format.html { render :edit }
        format.json { render json: @role.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= form_for(@role) do |f|
  - if @role.errors.any?
    = ar_errors_custom_view(@role)

  .field
    = f.label :name
    %br/
    = f.text_field :name, :class => 'form-control'
  .field
    = f.label :description
    %br/
    = f.text_field :description, :class => 'form-control'
  .actions
    = f.submit "Create Role", :class => "btn btn-default"

app/views/roles/edit.html.haml
%h2 Editing Role
= render 'form'
= link_to 'Show', @role
|
= link_to 'Back', roles_path

app/views/roles/index.html.haml
%h2 Listing Roles

.table-responsive
  %table.table.table-bordered
    %thead
      %tr
        %th Name
        %th Description
        %th Actions
    %tbody
      - @roles.each do |role|
        %tr
          %td= role.name
          %td= role.description
          %td
            = link_to 'Show', role, :class => "btn btn-success btn-sm active", :role => "button"
            = link_to 'Edit', edit_role_path(role), :class => "btn btn-warning btn-sm active", :role => "button"
            = link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm active", :role => "button"

= link_to 'New Role', new_role_path

app/views/roles/new.html.haml
%h2 New Role
= render 'form'
= link_to 'Back', roles_path

app/views/roles/show.html.haml
%p
  %strong Name:
  = @role.name
%p
  %strong Description:
  = @role.description
= link_to 'Edit', edit_role_path(@role)
|
= link_to 'Back', roles_path